VAGRANTFILE_API_VERSION = "2"
SITE_NAME = "BADCamp 2014"
MYSQL_PASSWORD = "badcamp"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "hashicorp/precise64"
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'" 
  config.vm.network "private_network", type: "dhcp" 

  config.vm.define "d8" do |d8|
    config.vm.hostname = "d8.dev"
    config.vm.synced_folder "www-d8", "/var/www/html", type: "nfs"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
  
    config.vm.provision "shell" do |s|
      s.privileged = false 
      s.path = "d8-provision.sh"
      s.args = [ MYSQL_PASSWORD, SITE_NAME ]
    end
  end

  config.vm.define "d7" do |d7|
    config.vm.hostname = "d7.dev"
    config.vm.synced_folder "www-d7", "/var/www", type: "nfs"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end

    config.vm.provision "shell" do |s|
      s.privileged = false
      s.path = "d7-provision.sh"
      s.args = [ MYSQL_PASSWORD, SITE_NAME ]
    end
  end
end
