VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "hashicorp/precise64"
  config.vm.network "private_network", ip: "192.168.8.8"
  config.vm.synced_folder "../www-shared", "/var/www/html", type: "nfs"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "d8" 
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end
  
  config.vm.hostname = "d8.dev"
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'" 
  config.vm.provision "shell" do |s|
    s.privileged = false 
    s.path = "provision.sh"
    s.args = [ "badcamp" ]
  end

end
